sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-rear-image .
script:
  # the "yast-travis-ruby" script is included in the base yastdevel/ruby image
  # see https://github.com/yast/docker-yast-ruby/blob/master/yast-travis-ruby
  # use "--privileged" so storage can access the devices
  - docker run --privileged -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-rear-image bash -c "yast-travis-ruby && ./integration_test.sh"
